package com.pricepulse.bd.ui.screens

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.material3.TopAppBarDefaults
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.pricepulse.bd.data.model.AnomalyDetail
import com.pricepulse.bd.ui.components.MetricRow
import com.pricepulse.bd.ui.components.SeverityBadge
import com.pricepulse.bd.ui.theme.PricePulseColors
import com.pricepulse.bd.viewmodel.PricePulseViewModel
import com.pricepulse.bd.viewmodel.UiState

/**
 * Anomaly Feed screen displaying flagged commodities with statistical breakdown.
 *
 * Each card shows the commodity name, severity badge, Z-score, Δ%, CV%, and
 * the human-readable explanation generated by the backend anomaly engine.
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun AnomalyScreen(viewModel: PricePulseViewModel) {
    val anomalyState by viewModel.anomalies.collectAsState()

    LaunchedEffect(Unit) {
        viewModel.loadAnomalyMonitor()
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = {
                    Column {
                        Text("Anomaly Monitor", fontWeight = FontWeight.Bold, fontSize = 18.sp)
                        Text("Statistical market alerts", color = PricePulseColors.Muted, fontSize = 12.sp)
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = MaterialTheme.colorScheme.surface,
                ),
            )
        },
        containerColor = MaterialTheme.colorScheme.background,
    ) { innerPadding ->
        when (val state = anomalyState) {
            is UiState.Idle, is UiState.Loading -> {
                Box(Modifier.fillMaxSize().padding(innerPadding), contentAlignment = Alignment.Center) {
                    CircularProgressIndicator(color = PricePulseColors.Indigo)
                }
            }
            is UiState.Error -> {
                Box(Modifier.fillMaxSize().padding(innerPadding), contentAlignment = Alignment.Center) {
                    Text(state.message, color = PricePulseColors.Rose, fontSize = 14.sp)
                }
            }
            is UiState.Success -> {
                val flagged = state.data.filter { it.isAnomaly }
                if (flagged.isEmpty()) {
                    Box(Modifier.fillMaxSize().padding(innerPadding), contentAlignment = Alignment.Center) {
                        Column(horizontalAlignment = Alignment.CenterHorizontally) {
                            Text("✓", fontSize = 40.sp, color = PricePulseColors.Emerald)
                            Spacer(Modifier.height(8.dp))
                            Text(
                                "All commodities operating within normal range.",
                                color = PricePulseColors.Muted,
                                fontSize = 14.sp,
                            )
                        }
                    }
                } else {
                    LazyColumn(
                        modifier = Modifier.fillMaxSize().padding(innerPadding),
                        contentPadding = PaddingValues(horizontal = 16.dp, vertical = 12.dp),
                        verticalArrangement = Arrangement.spacedBy(12.dp),
                    ) {
                        items(flagged) { anomaly ->
                            AnomalyCard(anomaly = anomaly)
                        }
                    }
                }
            }
        }
    }
}

@Composable
private fun AnomalyCard(anomaly: AnomalyDetail) {
    Column(
        modifier = Modifier
            .fillMaxWidth()
            .background(MaterialTheme.colorScheme.surface, RoundedCornerShape(12.dp))
            .padding(16.dp)
    ) {
        Row(
            modifier = Modifier.fillMaxWidth(),
            verticalAlignment = Alignment.CenterVertically,
        ) {
            Column(modifier = Modifier.weight(1f)) {
                Text(
                    text = anomaly.commodityName,
                    fontWeight = FontWeight.Bold,
                    fontSize = 15.sp,
                    color = MaterialTheme.colorScheme.onSurface,
                )
                if (!anomaly.banglaName.isNullOrBlank()) {
                    Text(
                        text = anomaly.banglaName,
                        color = PricePulseColors.Muted,
                        fontSize = 12.sp,
                    )
                }
            }
            SeverityBadge(severity = anomaly.severity)
        }

        Spacer(Modifier.height(12.dp))

        anomaly.metrics?.let { m ->
            MetricRow("Current Price", "BDT ${m.currentPrice ?: "—"}")
            MetricRow("14-Day SMA", "BDT ${m.sma14d ?: "—"}")
            MetricRow("Z-Score", "${m.zScore ?: "—"}",
                valueColor = if ((m.zScore ?: 0.0) > 2.5) PricePulseColors.Rose else PricePulseColors.Amber
            )
            MetricRow("Δ% from Baseline", "${m.deltaPct ?: "—"}%",
                valueColor = if ((m.deltaPct ?: 0.0) > 30) PricePulseColors.Rose else PricePulseColors.Amber
            )
            MetricRow("Volatility (CV%)", "${m.cvPct ?: "—"}%")
        }

        if (!anomaly.explanation.isNullOrBlank()) {
            Spacer(Modifier.height(12.dp))
            Text(
                text = anomaly.explanation,
                color = PricePulseColors.Muted,
                fontSize = 12.sp,
                lineHeight = 18.sp,
            )
        }
    }
}
