"""
setup_android_sdk.py — PricePulse BD
=====================================
Post-installation helper that:
1. Detects the Android SDK location from ANDROID_HOME or default path.
2. Writes android/local.properties with the correct sdk.dir for this machine.
3. Verifies JAVA_HOME is set and java is reachable.
4. Prints a checklist of what's ready and what still needs manual action in Android Studio.

Usage:
    python scripts/setup_android_sdk.py

Run this once after Android Studio has been installed and launched at least once
(so that it populates C:\\Users\\<USER>\\AppData\\Local\\Android\\Sdk).
"""

import os
import sys
import shutil
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
ANDROID_DIR  = PROJECT_ROOT / "android"
LOCAL_PROPS  = ANDROID_DIR / "local.properties"


def detect_sdk_path() -> Path | None:
    """Resolve Android SDK root from environment or known default location."""
    # 1. Explicit environment variable
    env_sdk = os.environ.get("ANDROID_HOME") or os.environ.get("ANDROID_SDK_ROOT")
    if env_sdk:
        p = Path(env_sdk)
        if p.exists():
            return p

    # 2. Windows default: %LOCALAPPDATA%\Android\Sdk
    local_app = os.environ.get("LOCALAPPDATA")
    if local_app:
        p = Path(local_app) / "Android" / "Sdk"
        if p.exists():
            return p

    # 3. macOS / Linux fallback
    home = Path.home()
    for candidate in [
        home / "Library" / "Android" / "sdk",
        home / "Android" / "Sdk",
    ]:
        if candidate.exists():
            return candidate

    return None


def detect_java_home() -> Path | None:
    java_home = os.environ.get("JAVA_HOME")
    if java_home:
        p = Path(java_home)
        if (p / "bin" / "java.exe").exists() or (p / "bin" / "java").exists():
            return p
    # Try shutil.which
    java_bin = shutil.which("java")
    if java_bin:
        return Path(java_bin).parent.parent
    return None


def write_local_properties(sdk_path: Path) -> None:
    """Write local.properties with the sdk.dir for this machine."""
    # Gradle requires forward slashes OR escaped backslashes on Windows
    sdk_escaped = str(sdk_path).replace("\\", "\\\\")
    content = (
        "# Auto-generated by scripts/setup_android_sdk.py — DO NOT commit this file.\n"
        "# This file is machine-specific and is listed in .gitignore.\n"
        f"sdk.dir={sdk_escaped}\n"
    )
    LOCAL_PROPS.write_text(content, encoding="utf-8")
    print(f"  ✓  Written: {LOCAL_PROPS}")
    print(f"     sdk.dir = {sdk_path}")


def check_sdk_components(sdk_path: Path) -> dict[str, bool]:
    """Verify which SDK components are present."""
    return {
        "platform-tools (adb)": (sdk_path / "platform-tools" / "adb.exe").exists(),
        "cmdline-tools":        (sdk_path / "cmdline-tools").exists(),
        "platforms (API 34)":   (sdk_path / "platforms" / "android-34").exists(),
        "build-tools 34":       any((sdk_path / "build-tools").glob("34.*")) if (sdk_path / "build-tools").exists() else False,
        "emulator":             (sdk_path / "emulator" / "emulator.exe").exists(),
        "system-images":        (sdk_path / "system-images").exists(),
    }


def main() -> int:
    print()
    print("=" * 60)
    print("  PricePulse BD — Android SDK Setup Helper")
    print("=" * 60)

    # --- Java ---
    java_home = detect_java_home()
    if java_home:
        print(f"  ✓  JAVA_HOME : {java_home}")
    else:
        print("  ✗  JAVA_HOME not found. Install Eclipse Temurin JDK 17:")
        print("     winget install --id EclipseAdoptium.Temurin.17.JDK -e --silent")

    # --- Android SDK ---
    sdk_path = detect_sdk_path()
    if not sdk_path:
        print()
        print("  ✗  Android SDK not found.")
        print()
        print("  ACTION REQUIRED:")
        print("  1. Open Android Studio (Start menu → Android Studio).")
        print("  2. Complete the Setup Wizard — let it download SDK components.")
        print("  3. Re-run this script:  python scripts/setup_android_sdk.py")
        print()
        # Write a placeholder local.properties pointing to the expected path
        expected = Path(os.environ.get("LOCALAPPDATA", "C:\\Users\\USER\\AppData\\Local")) / "Android" / "Sdk"
        print(f"  Expected SDK path after Studio setup: {expected}")
        return 1

    print(f"  ✓  ANDROID_HOME: {sdk_path}")
    print()

    # Write local.properties
    write_local_properties(sdk_path)
    print()

    # Component checklist
    components = check_sdk_components(sdk_path)
    print("  SDK Component Checklist:")
    all_ok = True
    for name, present in components.items():
        mark = "✓" if present else "✗"
        print(f"    {mark}  {name}")
        if not present:
            all_ok = False

    if not all_ok:
        print()
        print("  Some components are missing. Open Android Studio →")
        print("  Tools → SDK Manager and install:")
        print("    • Android SDK Platform 34")
        print("    • Android SDK Build-Tools 34")
        print("    • Android SDK Command-line Tools (latest)")
        print("    • Android Emulator")
        print("    • Google APIs Intel x86_64 Atom System Image (API 34)")

    print()
    print("  Gradle Wrapper Files:")
    for f in ["gradlew.bat", "gradlew", "gradle/wrapper/gradle-wrapper.jar",
              "gradle/wrapper/gradle-wrapper.properties"]:
        p = ANDROID_DIR / f
        mark = "✓" if p.exists() else "✗"
        print(f"    {mark}  android/{f}")

    print()
    if all_ok:
        print("  ✅  All components present. Open the project in Android Studio:")
        print(f"     File → Open → {ANDROID_DIR}")
        print()
        print("  Or build from the command line (after Studio initial sync):")
        print("     cd android")
        print("     .\\gradlew.bat assembleDebug")
    else:
        print("  ⚠   Complete the SDK Manager steps above, then run:")
        print("     python scripts/setup_android_sdk.py")

    print()
    return 0 if all_ok else 1


if __name__ == "__main__":
    sys.exit(main())
